### ISSUE TITLE
Display formulas with $$ not working

### ISSUE THREAD

**Issue by jluttine** [stevenkaras/stevenkaras.github.com#1]
Hi!

I found your interesting blog post:

https://karas.io/blog/math-support-with-katex-on-github-pages/

This was great, just what I was looking for, thanks! However, I noticed that the display formula with $$ doesn't render. I tried it locally and it works, so it's something to do with GitHub pages. Any ideas what could be wrong? Perhaps you want to fix your post, and I would also like to have this feature working on my site..

**Comment by jluttine** [comment]
I added this to the end of the file and then it seems to work:

```
<script type="text/javascript">
document.querySelectorAll("script[type='math/tex']").forEach(function(el) {
  el.outerHTML = katex.renderToString(el.textContent, { displayMode: false });
});

document.querySelectorAll("script[type='math/tex; mode=display']").forEach(function(el) {
  el.outerHTML = katex.renderToString(el.textContent.replace(/%.*/g, ''), { displayMode: true });
});
</script>
```

I just copy pasted it from https://github.com/gettalong/kramdown/issues/292#issuecomment-313266061 so I don't really know what I'm doing. Perhaps you have better insight how to solve this "correctly".

**Comment by stevenkaras** [comment]
It works for me (FF/14.04). What browser are you using/adblocker?

I see that the context for that fix is for IE. I might be able to take a look later this week, but I'll want to confirm the fix and that it doesn't break for other browsers before I make any changes.

**Comment by jluttine** [comment]
I have Firefox 58.0.2. I disabled uBlock Origin, but the equation still didn't show up.

By the way, GitLab pages supports Jekyll plugins, and actually whatever static site builders and build processes. I learned this yesterday, so I'll probably move there so I can do server side KaTeX rendering with Jekyll plugins.

**Comment by stevenkaras** [comment]
Very odd. Can you open the console and see if there are any JS errors there?

Not really interested in migrating to Gitlab at the moment.

**Comment by jluttine** [comment]
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified

**Comment by stevenkaras** [comment]
Looking at this fresh, it's 100% not rendering correctly. It seems that GHP are [forcing the kramdown engine to use mathjax][0]. I'm fairly certain this is new, and there used to be the option to disable it.

As is, this means that if you want to use GHP, you'll need to either use the `\\[` delimiter to have a graceful fallback, and I'll update my template to render katex correctly for mathjax blocks. I've contacted Github support and hopefully they'll clear when/why this decision was made.

[0]: https://github.com/github/pages-gem/blob/e7eb0a956fa66ddac3bafdd8fa6b8e5ccbd9bf20/lib/github-pages/configuration.rb#L54

EDIT: Apparently this was always the case and I never checked that it worked correctly. Thanks to GitHub support for pointing me in the right direction.

**Comment by stevenkaras** [comment]
I've updated my katex integration, and it should render correctly now (kramdown only mangles the display blocks)
